/**
 * Code Snippets Library — common code patterns organized by language.
 * Users can insert these into the editor with one click.
 */

export interface Snippet {
  id: string;
  label: string;
  description: string;
  language: string;
  category: string;
  code: string;
}

export const SNIPPETS: Snippet[] = [
  // --- HTML ---
  { id: 'html-navbar', label: 'Navbar', description: 'Responsive navigation bar', language: 'html', category: 'HTML', code: '<nav style="display:flex;justify-content:space-between;align-items:center;padding:16px 24px;background:#1a1a2e;color:white;">\n  <div style="font-weight:bold;font-size:20px;">MyApp</div>\n  <div style="display:flex;gap:20px;">\n    <a href="#" style="color:white;text-decoration:none;">Home</a>\n    <a href="#" style="color:white;text-decoration:none;">About</a>\n    <a href="#" style="color:white;text-decoration:none;">Contact</a>\n  </div>\n</nav>' },
  { id: 'html-form', label: 'Login Form', description: 'Email + password form', language: 'html', category: 'HTML', code: '<form style="max-width:400px;margin:40px auto;padding:24px;border-radius:12px;box-shadow:0 4px 20px rgba(0,0,0,0.1);font-family:system-ui;">\n  <h2 style="margin:0 0 20px;">Login</h2>\n  <div style="margin-bottom:16px;">\n    <label style="display:block;margin-bottom:4px;font-size:14px;">Email</label>\n    <input type="email" placeholder="you@example.com" style="width:100%;padding:10px;border:1px solid #ddd;border-radius:6px;font-size:14px;">\n  </div>\n  <div style="margin-bottom:16px;">\n    <label style="display:block;margin-bottom:4px;font-size:14px;">Password</label>\n    <input type="password" placeholder="••••••••" style="width:100%;padding:10px;border:1px solid #ddd;border-radius:6px;font-size:14px;">\n  </div>\n  <button type="submit" style="width:100%;padding:12px;background:#7c83ff;color:white;border:none;border-radius:6px;font-size:15px;cursor:pointer;">Login</button>\n</form>' },
  { id: 'html-card', label: 'Card', description: 'Content card with image', language: 'html', category: 'HTML', code: '<div style="max-width:350px;border-radius:12px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);font-family:system-ui;">\n  <div style="height:180px;background:linear-gradient(135deg,#667eea,#764ba2);"></div>\n  <div style="padding:20px;">\n    <h3 style="margin:0 0 8px;">Card Title</h3>\n    <p style="margin:0;color:#666;font-size:14px;">This is a card component with a gradient header and content area.</p>\n  </div>\n</div>' },
  { id: 'html-table', label: 'Table', description: 'Styled data table', language: 'html', category: 'HTML', code: '<table style="width:100%;border-collapse:collapse;font-family:system-ui;">\n  <thead>\n    <tr style="background:#7c83ff;color:white;">\n      <th style="padding:12px;text-align:left;">Name</th>\n      <th style="padding:12px;text-align:left;">Email</th>\n      <th style="padding:12px;text-align:left;">Role</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr style="border-bottom:1px solid #eee;">\n      <td style="padding:12px;">Alice</td>\n      <td style="padding:12px;">alice@example.com</td>\n      <td style="padding:12px;">Admin</td>\n    </tr>\n    <tr style="border-bottom:1px solid #eee;">\n      <td style="padding:12px;">Bob</td>\n      <td style="padding:12px;">bob@example.com</td>\n      <td style="padding:12px;">User</td>\n    </tr>\n  </tbody>\n</table>' },
  { id: 'html-grid', label: 'Grid Layout', description: 'CSS Grid gallery', language: 'html', category: 'HTML', code: '<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:16px;padding:20px;">\n  <div style="height:150px;background:#667eea;border-radius:8px;"></div>\n  <div style="height:150px;background:#764ba2;border-radius:8px;"></div>\n  <div style="height:150px;background:#f093fb;border-radius:8px;"></div>\n  <div style="height:150px;background:#4facfe;border-radius:8px;"></div>\n  <div style="height:150px;background:#43e97b;border-radius:8px;"></div>\n  <div style="height:150px;background:#fa709a;border-radius:8px;"></div>\n</div>' },

  // --- CSS ---
  { id: 'css-flexbox', label: 'Flexbox Center', description: 'Perfect centering', language: 'css', category: 'CSS', code: 'display: flex;\njustify-content: center;\nalign-items: center;\nmin-height: 100vh;' },
  { id: 'css-gradient', label: 'Gradient BG', description: 'Animated gradient background', language: 'css', category: 'CSS', code: 'background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);\nbackground-size: 400% 400%;\nanimation: gradientFlow 15s ease infinite;\n\n@keyframes gradientFlow {\n  0% { background-position: 0% 50%; }\n  50% { background-position: 100% 50%; }\n  100% { background-position: 0% 50%; }\n}' },
  { id: 'css-glass', label: 'Glassmorphism', description: 'Frosted glass effect', language: 'css', category: 'CSS', code: 'background: rgba(255, 255, 255, 0.15);\nbackdrop-filter: blur(10px);\n-webkit-backdrop-filter: blur(10px);\nborder: 1px solid rgba(255, 255, 255, 0.2);\nborder-radius: 16px;\nbox-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);' },
  { id: 'css-button', label: 'Gradient Button', description: 'Modern gradient button', language: 'css', category: 'CSS', code: 'button {\n  background: linear-gradient(135deg, #667eea, #764ba2);\n  color: white;\n  border: none;\n  padding: 14px 32px;\n  border-radius: 8px;\n  font-size: 16px;\n  cursor: pointer;\n  transition: transform 0.2s, box-shadow 0.2s;\n}\nbutton:hover {\n  transform: translateY(-2px);\n  box-shadow: 0 8px 20px rgba(102, 126, 234, 0.4);\n}\nbutton:active {\n  transform: translateY(0);\n}' },
  { id: 'css-input', label: 'Neon Input', description: 'Glowing text input', language: 'css', category: 'CSS', code: 'input {\n  padding: 12px 16px;\n  border: 2px solid #2d2d4a;\n  border-radius: 8px;\n  background: #1a1a2e;\n  color: #e0e0f0;\n  font-size: 15px;\n  outline: none;\n  transition: border-color 0.3s, box-shadow 0.3s;\n}\ninput:focus {\n  border-color: #7c83ff;\n  box-shadow: 0 0 0 3px rgba(124, 131, 255, 0.2);\n}' },

  // --- JavaScript ---
  { id: 'js-fetch', label: 'Fetch API', description: 'GET request with async/await', language: 'javascript', category: 'JavaScript', code: 'async function fetchData(url) {\n  try {\n    const response = await fetch(url);\n    if (!response.ok) throw new Error("HTTP " + response.status);\n    const data = await response.json();\n    console.log("Data:", data);\n    return data;\n  } catch (error) {\n    console.error("Fetch error:", error.message);\n  }\n}\n\n// fetchData("https://api.example.com/data");' },
  { id: 'js-debounce', label: 'Debounce', description: 'Delay function execution', language: 'javascript', category: 'JavaScript', code: 'function debounce(fn, delay = 300) {\n  let timer;\n  return function(...args) {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn.apply(this, args), delay);\n  };\n}\n\n// const debouncedSearch = debounce((q) => console.log("Searching:", q), 500);\n// debouncedSearch("hello");' },
  { id: 'js-localStorage', label: 'localStorage', description: 'Save and load data', language: 'javascript', category: 'JavaScript', code: '// Save data\nlocalStorage.setItem("user", JSON.stringify({ name: "Alice", age: 28 }));\n\n// Load data\nconst user = JSON.parse(localStorage.getItem("user") || "{}");\nconsole.log("Loaded user:", user);\n\n// Remove data\n// localStorage.removeItem("user");\n\n// Clear all\n// localStorage.clear();' },
  { id: 'js-event', label: 'Event Listener', description: 'Click handler with delegation', language: 'javascript', category: 'JavaScript', code: 'document.addEventListener("click", function(e) {\n  // Event delegation — check what was clicked\n  if (e.target.matches("[data-action]")) {\n    const action = e.target.dataset.action;\n    console.log("Action:", action);\n  }\n});\n\n// Add data-action attributes: <button data-action="save">Save</button>' },
  { id: 'js-map-filter', label: 'Map & Filter', description: 'Array transformations', language: 'javascript', category: 'JavaScript', code: 'const users = [\n  { name: "Alice", age: 28, active: true },\n  { name: "Bob", age: 34, active: false },\n  { name: "Charlie", age: 22, active: true },\n];\n\n// Filter active users\nconst active = users.filter(u => u.active);\nconsole.log("Active:", active.map(u => u.name));\n\n// Get names\nconst names = users.map(u => u.name);\nconsole.log("Names:", names);\n\n// Find by name\nconst alice = users.find(u => u.name === "Alice");\nconsole.log("Found:", alice);\n\n// Sort by age\nconst sorted = [...users].sort((a, b) => a.age - b.age);\nconsole.log("Sorted by age:", sorted.map(u => u.name));' },
  { id: 'js-clock', label: 'Digital Clock', description: 'Live updating clock', language: 'javascript', category: 'JavaScript', code: 'function updateClock() {\n  const now = new Date();\n  const time = now.toLocaleTimeString();\n  console.log(time);\n}\n\nsetInterval(updateClock, 1000);\nupdateClock();' },

  // --- TypeScript ---
  { id: 'ts-interface', label: 'Interface', description: 'Type definitions', language: 'typescript', category: 'TypeScript', code: 'interface User {\n  id: number;\n  name: string;\n  email: string;\n  role: "admin" | "user" | "guest";\n  preferences?: {\n    theme: "dark" | "light";\n    notifications: boolean;\n  };\n}\n\nconst user: User = {\n  id: 1,\n  name: "Alice",\n  email: "alice@example.com",\n  role: "admin",\n  preferences: { theme: "dark", notifications: true },\n};\n\nconsole.log(user);' },
  { id: 'ts-generic', label: 'Generic Function', description: 'Reusable typed function', language: 'typescript', category: 'TypeScript', code: 'function groupBy<T, K extends keyof T>(items: T[], key: K): Record<string, T[]> {\n  return items.reduce((groups, item) => {\n    const groupKey = String(item[key]);\n    (groups[groupKey] = groups[groupKey] || []).push(item);\n    return groups;\n  }, {} as Record<string, T[]>);\n}\n\nconst users = [\n  { name: "Alice", dept: "Eng" },\n  { name: "Bob", dept: "Sales" },\n  { name: "Charlie", dept: "Eng" },\n];\n\nconsole.log(groupBy(users, "dept"));' },

  // --- Python ---
  { id: 'py-list-comp', label: 'List Comprehension', description: 'Filter and transform lists', language: 'python', category: 'Python', code: 'numbers = range(1, 20)\n\n# Squares of even numbers\nsquares = [n**2 for n in numbers if n % 2 == 0]\nprint("Even squares:", squares)\n\n# Flatten a 2D list\nmatrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]\nflat = [num for row in matrix for num in row]\nprint("Flattened:", flat)' },
  { id: 'py-dict', label: 'Dictionary', description: 'Dict operations', language: 'python', category: 'Python', code: '# Create\nuser = {"name": "Alice", "age": 28, "city": "Kampala"}\n\n# Access\nprint(user["name"])\nprint(user.get("email", "N/A"))\n\n# Iterate\nfor key, value in user.items():\n    print(f"{key}: {value}")\n\n# Merge\nextended = {**user, "email": "alice@example.com", "role": "admin"}\nprint(extended)' },
  { id: 'py-class', label: 'Class', description: 'Simple class with methods', language: 'python', category: 'Python', code: 'class Animal:\n    def __init__(self, name, sound):\n        self.name = name\n        self.sound = sound\n\n    def speak(self):\n        return f"{self.name} says {self.sound}!"\n\nclass Dog(Animal):\n    def __init__(self, name):\n        super().__init__(name, "Woof")\n\n    def fetch(self):\n        return f"{self.name} fetches the ball!"\n\ndog = Dog("Rex")\nprint(dog.speak())\nprint(dog.fetch())' },

  // --- JSON ---
  { id: 'json-config', label: 'Config Object', description: 'App configuration', language: 'json', category: 'JSON', code: '{\n  "name": "my-app",\n  "version": "1.0.0",\n  "api": {\n    "baseUrl": "https://api.example.com",\n    "timeout": 5000,\n    "retries": 3\n  },\n  "features": ["auth", "dashboard", "settings"],\n  "theme": {\n    "primary": "#7c83ff",\n    "dark": true\n  }\n}' },
];

/** Get snippets filtered by language */
export function getSnippetsByLanguage(language: string): Snippet[] {
  return SNIPPETS.filter(s => s.language === language);
}

/** Get all unique categories */
export function getCategories(): string[] {
  return [...new Set(SNIPPETS.map(s => s.category))];
}
